name: experimental

on: 
  push:
    branches:
      - master

jobs:
  experimental:
    name: experimental
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for check.sh
        run: chmod +x ./.github/scripts/check.sh
      - name: Run scrip
        run: |
          ./.github/scripts/check.sh /
          ./.github/scripts/check_v.sh
