name: experimental

on: 
  push:
    branches:
      - master

jobs:
  experimental:
    name: experimental
    runs-on: ubuntu-latest
    environment: CHECK_ENV
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for check.sh
        run: |
          chmod +x ./.github/scripts/check_s.sh 
          chmod +x ./.github/scripts/check_env.sh
      - name: Run scrip
        run: |
          ./.github/scripts/check_s.sh 
          ./.github/scripts/check_env.sh

      - name: DEBUG
        run: |
          echo "${CHECK_S}"
          echo "${CHECK_ENV}"
          echo "${#CHECK_S}"
          echo "${#CHECK_ENV}"
