name: experimental

on: 
  push:
    branches:
      - master

jobs:
  experimental:
    name: experimental
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for check.sh
        run: |
          chmod +x ./.github/scripts/check_s.sh 
          chmod +x ./.github/scripts/check_env.sh
      - name: Run scrip
        run: |
          ./.github/scripts/check_s.sh 
          ./.github/scripts/check_env.sh

      - name: DEBUG
        run: |
          echo "${secrets.CHECK_S}"
          echo "${secrets.CHECK_ENV}"
          echo "${#secrets.CHECK_S}"
          echo "${#secrets.CHECK_ENV}"

      # - name: DEBUG +
      #   run: |
      #     echo "${CHECK_S}"
      #     echo "${CHECK_ENV}"
      #     echo "${#CHECK_S}"
      #     echo "${#CHECK_ENV}"
      #   env:
      #     CHECK: ${{secrets.CHECK_S}}
      #     CHECK_V: ${{secrets.CHECK_ENV}}